id: qrcode_1
name: MedExpress_Code
version: 2.0.4
author: ZeroHzzzz
icon: ''
desc: 扫描二维码，发送串口信息
files:
  - .python-version
  - barcode.py
  - correction.py
  - main.py
  - pyproject.toml
  - qrcode.py
  - README.md
  - uv.lock
