[project]
name = "medexpress-qrcode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "imutils>=0.5.4",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
    "pyzbar>=0.1.8",
]
